### PR TITLE
#18 Fix image add command when partial image alias match exists

### LINKED ISSUE #18: Image add command fails when partial image alias match exists
Given:
- Image with alias `nod` **does not** exist
- Image with alias `nod2` **does** exist

When:
- Command `/image add nod <some image url>` is issued

Then:
- Image add command fails

Expected:
- Image add command succeeds

### PR DESCRIPTION
**Pull request by erichaagdev**
This bug would occur when an image add command is issued for an image alias that partially matches to an existing image alias. In other words:

Given:
- Image with alias `nod` **does not** exist
- Image with alias `nod2` **does** exist

When:
- Command `image add nod <some image url>` is issued

Then:
- Image add command fails

An image should be able to be added as long as there is not an **exact** alias match. To fix this, I broke the `getImage()` method in the `ImageHelper` class into two separate methods:
1. `getImage()` to just return results for exact alias matches
2. `getFuzzyImage()` which will first perform an exact match and if no images are found, a fuzzy search is performed to try and find a suitable image

In addition to the above fix, the following additions have been added:
- Several integration tests, including one that covers this scenario
- `DefaultCommandAdapter` which will be used when no other command adapter can be found
- SpringDoc page which can be used to test commands from the browser, visible at `/swagger-ui.html`.

- Closes #18

### CODE REVIEW

File: src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java [hunk 1]
```diff
@@ -1,12 +1,33 @@
...
+
 @Value
+@Builder
+@AllArgsConstructor
+@Schema(example = """
+        {
+          "author": "Gorlah",
+          "message": "hello"
+        }
+        """)
```
Comment (ploober) [inline src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java]: nice text block bro

File: src/main/java/com/gorlah/kappabot/function/command/DefaultCommandAdapter.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
+package com.gorlah.kappabot.function.command;
+
+import com.gorlah.kappabot.util.StandardContentTypes;
+import lombok.RequiredArgsConstructor;
+import org.springframework.beans.factory.annotation.Value;
+import org.springframework.stereotype.Component;
+
+@Component
+@RequiredArgsConstructor
```
Comment (ploober) [inline src/main/java/com/gorlah/kappabot/function/command/DefaultCommandAdapter.java]: there are no required args

File: src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java (hunk 1 above)
Comment (ploober) [reply src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java]: should the example show the optional field source?

File: src/main/java/com/gorlah/kappabot/rest/validation/ValidationControllerAdvice.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+import org.springframework.web.bind.annotation.ExceptionHandler;
+import org.springframework.web.bind.annotation.ResponseBody;
+import org.springframework.web.bind.annotation.ResponseStatus;
+import org.springframework.web.bind.annotation.RestControllerAdvice;
+
+import javax.validation.ConstraintViolationException;
+import java.util.stream.Collectors;
+
+@RestControllerAdvice
+class ValidationControllerAdvice {
```
Comment (ploober) [inline src/main/java/com/gorlah/kappabot/rest/validation/ValidationControllerAdvice.java:15]: 👌

File: src/main/java/com/gorlah/kappabot/rest/validation/ValidationErrorResponse.java [hunk 4]
```diff
@@ -0,0 +1,22 @@
+package com.gorlah.kappabot.rest.validation;
+
+import io.swagger.v3.oas.annotations.media.Schema;
+import lombok.Value;
+
+import java.util.List;
+
+@Value
+class ValidationErrorResponse {
```
Comment (ploober) [inline src/main/java/com/gorlah/kappabot/rest/validation/ValidationErrorResponse.java]: If you had more REST endpoints in your app or were officially exposing this API as a production-ready feature to be used for integration with other systems, I would suggest coming up with a common model for all errors (so every kind of exception could be mapped to a JSON object) and have the validation response be an instance of your standard error response that also has the listed validation errors. Since this endpoint is the only endpoint, and only intended to be used for debugging, this not a concern.

**Comment by ploober** [comment]
Hmmmm.

Request:
```json
{
  "message": "/kb image search g",
  "author": "ploober"
}
```

Response:
```json
{
  "response": "I didn't find anything for `/kbg`."
}
```

File: src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java (hunk 1 above)
Comment (erichaagdev) [reply src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java]: It could, but it would be slightly misleading since it's going to use the default if you don't have a discord integration turned on. I think the default example should represent functionality that works right out of the box. You can see the full schema, which shows the optional source field, by clicking from `Example Value` to `Schema`. 

firefox_busl54snYS

**Comment by ploober** [comment]
Ya busted it.

Request:
```json
{
  "message": "https://m.slashdot.org/story/375986",
  "author": "ploober",
  "source": "discord"
}
```

Response:
```json
{
  "response": "Try adding one of the following subcommands to `/kb`: code , hello , image , meme \nOr use `/kb help`\n-----------------------\n> Last-Minute TikTok Deal Averts Shutdown"
}
```

I liked the plain text output better than JSON but its not a big deal.

**Review by ploober — CHANGES_REQUESTED** [review]
Needs work :-1:

File: src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java (hunk 1 above)
Comment (ploober) [reply src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java]: Yeah it works without specifying a source now, but I thought that was considered a fallback behavior. I considered the purpose of this endpoint as a way to debug handling of a real source.

Edit: as long as it lists it either way, it doesn't really need the example per-se.

Comment (erichaagdev) [reply src/main/java/com/gorlah/kappabot/rest/model/CommandRequest.java]: I guess it just depends on how you look at it. I know it has never really turned into this, but I always tried to make this version of KappaBot as extensible as possible. Starting with HipChat, Discord, and (eventually?) Teams, I've rewritten the project basically 3 different times. The core of the command processing remained the same, it was just the sources that changed. So as applications come and go, I think it makes sense to just have a "default" behavior that integrates to nothing. 

If I need to test Discord I can add `"source": "discord"`, or also OpenAPI supports multiple examples so I could technically add a default and Discord example.

File: src/main/java/com/gorlah/kappabot/rest/validation/ValidationErrorResponse.java (hunk 4 above)
Comment (erichaagdev) [reply src/main/java/com/gorlah/kappabot/rest/validation/ValidationErrorResponse.java]: That would actually be pretty cool. Do you basically just write a `ControllerAdvice` that would handle `Exception.class`? Then return the exception's message as a 500? Although I guess some exceptions could be more suitable for 400 exceptions.

Comment (ploober) [reply src/main/java/com/gorlah/kappabot/rest/validation/ValidationErrorResponse.java]: Yeah, you would have some kind of advice or other exception handling mechanism that handles all `Exception` and you can have more specific things like your validation errors still be handled specially, and then in general fall back to returning a 500 error and maybe a concise message, but if you have all your errors return a consistent model it can make things easier for your API clients. 

One thing I recently started including in my error objects that I am happy with is a unique reference ID that is generated when the exception is being translated into my error object. That way I can leave the stacktrace out of the response but still be able to tie that response back to the stacktrace by searching the server log for the unique ID.

**Comment by erichaagdev** [comment]
@ploober I believe I have addressed all of the above issues. 

As I had mentioned, I ended up requiring the specification of a source. The SpringDoc example defaults to `{"source": "default"}`. I also changed the default command adapter to require a prefix of `/kb`. This is so that the default command adapter is not triggered for other functions, like the Slashdot parser.

**Comment by ploober** [comment]
Do the tests pass for you?
```
processHelloThere()
java.lang.AssertionError: 1 expectation failed.
JSON path response doesn't match.
Expected: General Gorlah!
  Actual: null

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
```

**Comment by ploober** [comment]
Notice the trailing space in the message.

Request:
```json
{
  "message": "/kb",
  "author": "ploober",
  "source": "default"
}
```

Response: empty

---

Request:
```json
{
  "message": "/kb ",
  "author": "ploober",
  "source": "default"
}
```

Response:
```
Try adding one of the following subcommands to /kb: code , hello , image , meme
Or use /kb help
```

**Review by ploober — CHANGES_REQUESTED** [review]
I think we want it to respond with the help text when there isn't a trailing space on the message. Good candidate for a test case too.

**Comment by erichaagdev** [comment]
> I think we want it to respond with the help text when there isn't a trailing space on the message. Good candidate for a test case too.

Good catch. Fixed. The test cases were an easy addition and I also removed the unnecessary spaces surrounding the comma in the help text e.g. from:
`Try adding one of the following subcommands to /kb: code , hello , image , meme`

To:
`Try adding one of the following subcommands to /kb: code, hello, image, meme`

**Review by ploober — APPROVED** [review]
Looks good now

**Comment by ploober** [comment]
Nice adding the CI check
